CREATE TABLE "TBL_USER" 
   (	"ID" NUMBER(19,0) NOT NULL, 
	"IS_PERMANENT" NUMBER(1,0), 
	"DISPLAY_NAME" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"SUR_NAME" VARCHAR2(255 CHAR), 
	"OCCUPATION" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR) NOT NULL, 
	 PRIMARY KEY ("ID")
	 
	 );
   
  CREATE TABLE "TBL_USER_USERADDRESSES" 
   (	"TBL_USER_USERID" NUMBER(19,0) NOT NULL, 
	"CITY" VARCHAR2(255 CHAR), 
	"COUNTRY" VARCHAR2(255 CHAR), 
	"IS_PRIMARY" NUMBER(1,0), 
	"REGION" VARCHAR2(255 CHAR), 
	"STREET" VARCHAR2(255 CHAR), 
	"UNIT" VARCHAR2(255 CHAR), 
	"ZIPCODE" NUMBER(19,0)
   ) ;

  CREATE TABLE "TBL_USER_USERCONTACTS" 
   (	"TBL_USER_USERID" NUMBER(19,0) NOT NULL, 
	"EMAIL_ADDRESS" VARCHAR2(255 CHAR), 
	"MOBILE_NUMBER" VARCHAR2(255 CHAR)
   ); 